# Generated by Django 5.1.3 on 2025-07-17 00:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("billing", "0001_initial"),
        ("core", "0001_initial"),
        ("doctors", "0001_initial"),
        ("patients", "0001_initial"),
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentmaster",
            name="hospital",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.hospital"
            ),
        ),
        migrations.AddField(
            model_name="paymentmaster",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="patients.patient"
            ),
        ),
        migrations.AddField(
            model_name="paymenttransaction",
            name="doctor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="doctors.doctor"
            ),
        ),
        migrations.AddField(
            model_name="paymenttransaction",
            name="hospital",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.hospital"
            ),
        ),
        migrations.AddField(
            model_name="paymenttransaction",
            name="patient",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="patients.patient",
            ),
        ),
        migrations.AddField(
            model_name="paymenttransaction",
            name="payment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transactions",
                to="billing.paymentmaster",
            ),
        ),
        migrations.AddField(
            model_name="paymenttransaction",
            name="service",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="services.service"
            ),
        ),
        migrations.AddIndex(
            model_name="paymentmaster",
            index=models.Index(
                fields=["paid_on"], name="billing_pay_paid_on_4317df_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymentmaster",
            index=models.Index(
                fields=["patient"], name="billing_pay_patient_7b3f89_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymentmaster",
            index=models.Index(
                fields=["hospital"], name="billing_pay_hospita_c9a676_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymenttransaction",
            index=models.Index(
                fields=["payment"], name="billing_pay_payment_14b8f5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymenttransaction",
            index=models.Index(
                fields=["doctor"], name="billing_pay_doctor__fc54cf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymenttransaction",
            index=models.Index(
                fields=["service"], name="billing_pay_service_462223_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymenttransaction",
            index=models.Index(
                fields=["paid_on"], name="billing_pay_paid_on_e00c9a_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="paymenttransaction",
            unique_together={("patient", "doctor", "service", "hospital", "paid_on")},
        ),
    ]
