# Generated by Django 5.1.3 on 2025-08-14 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0002_initial"),
    ]

    operations = []
