# Generated by Django 4.2.14 on 2025-09-06 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_backfill_tx_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttransaction',
            name='pay_type',
            field=models.CharField(choices=[('Due', 'Due'), ('Cash', 'Cash'), ('Card', 'Card'), ('UPI', 'UPI'), ('Insurance', 'Insurance'), ('Other', 'Other')], max_length=20),
        ),
    ]
