# Generated by Django 4.2.14 on 2025-10-23 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_alter_paymenttransaction_pay_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttransaction',
            name='pay_type',
            field=models.CharField(choices=[('Due', 'Due'), ('Cash', 'Cash'), ('Card', 'Card'), ('UPI', 'UPI'), ('Review', 'Review'), ('Other', 'Other')], max_length=20),
        ),
    ]
