# Generated by Django 5.1.3 on 2025-07-26 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        ("doctors", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="hospitaluser",
            name="doctor",
            field=models.OneToOneField(
                blank=True,
                help_text="If this user is a doctor, their Doctor profile",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="doctors.doctor",
            ),
        ),
        migrations.AlterField(
            model_name="hospitaluser",
            name="hospital",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="users",
                to="core.hospital",
            ),
        ),
    ]
