# Generated by Django 5.1.3 on 2025-07-26 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_hospitaluser_doctor_alter_hospitaluser_hospital"),
        ("doctors", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hospitaluser",
            name="doctor",
            field=models.OneToOneField(
                blank=True,
                help_text="Linked Doctor profile (if this user is a doctor)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="doctors.doctor",
            ),
        ),
    ]
