# Generated by Django 5.1.3 on 2025-07-26 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_hospitaluser_doctor"),
    ]

    operations = [
        migrations.AddField(
            model_name="hospitaluser",
            name="display_name",
            field=models.CharField(
                blank=True,
                help_text="Optional name shown in the UI",
                max_length=255,
                null=True,
            ),
        ),
    ]
