# Generated by Django 4.2.14 on 2025-11-04 19:32

from django.db import migrations, models
from django.utils.text import slugify


def populate_slugs(apps, schema_editor):
    Hospital = apps.get_model("core", "Hospital")
    for h in Hospital.objects.filter(slug__isnull=True):
        base_slug = slugify(h.hospital_name)
        slug = base_slug
        counter = 1
        # Ensure uniqueness
        while Hospital.objects.filter(slug=slug).exists():
            slug = f"{base_slug}-{counter}"
            counter += 1
        h.slug = slug
        h.save(update_fields=["slug"])


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_hospitaluser_consult_message_template_and_more"),
    ]

    operations = [
        # Step 1: add slug column temporarily allowing NULLs
        migrations.AddField(
            model_name="hospital",
            name="slug",
            field=models.SlugField(max_length=100, unique=True, null=True, blank=True),
        ),
        # Step 2: populate slugs for existing hospitals
        migrations.RunPython(populate_slugs, reverse_code=migrations.RunPython.noop),
        # Step 3: enforce NOT NULL after population
        migrations.AlterField(
            model_name="hospital",
            name="slug",
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
