# Generated by Django 4.2.14 on 2025-11-05 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_hospital_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
    ]
