# Generated by Django 4.2.14 on 2025-11-29 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_hospital_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='ai_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
