# Generated by Django 4.2.14 on 2025-12-06 12:00

from django.db import migrations
from django.db import migrations

def normalize_roles(apps, schema_editor):
    Role = apps.get_model("core", "Role")
    HospitalUser = apps.get_model("core", "HospitalUser")

    # Mapping old → canonical lowercase roles
    mapping = {
        "reception": "reception",
        "receptionist": "reception",

        "administrator": "hospital_admin",
        "admin": "hospital_admin",
        "hospital_admin": "hospital_admin",

        "doctor": "doctor",
        "md": "doctor",

        "accountant": "accountant",

        "superadmin": "super_admin",
        "super admin": "super_admin",
        "super_admin": "super_admin",
    }

    # Normalize Role table
    for role in Role.objects.all():
        old_name = (role.role_name or "").strip().lower()
        new_name = mapping.get(old_name)
        if new_name:
            role.role_name = new_name
            role.save(update_fields=["role_name"])

    # Normalize assigned roles on HospitalUser
    for user in HospitalUser.objects.select_related("role"):
        if not user.role:
            continue
        old_name = (user.role.role_name or "").strip().lower()
        new_name = mapping.get(old_name)
        if new_name and old_name != new_name:
            # Find matching normalized role
            new_role_obj, _ = Role.objects.get_or_create(role_name=new_name)
            user.role = new_role_obj
            user.save(update_fields=["role"])

def reverse_normalize_roles(apps, schema_editor):
    """
    No-op reverse. Role normalization is irreversible.
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_hospital_ai_enabled'),
    ]

    operations = [
    ]
