# Generated by Django 4.2.14 on 2025-12-06 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_normalize_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='role_name',
            field=models.CharField(choices=[('hospital_admin', 'hospital_admin'), ('reception', 'reception'), ('doctor', 'doctor'), ('accountant', 'accountant'), ('super_admin', 'super_admin')], max_length=50, unique=True),
        ),
    ]
