# Generated by Django 4.2.14 on 2025-09-25 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappmessagelog',
            name='buttons',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
