# Generated by Django 4.2.14 on 2025-09-25 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_notifications', '0002_whatsappmessagelog_buttons'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whatsappconfig',
            name='api_key',
        ),
        migrations.RemoveField(
            model_name='whatsappconfig',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='whatsappconfig',
            name='provider',
        ),
        migrations.RemoveField(
            model_name='whatsappconfig',
            name='webhook_url',
        ),
    ]
