# Generated by Django 4.2.14 on 2025-09-26 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_notifications', '0003_remove_whatsappconfig_api_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappconfig',
            name='confirmation_template',
            field=models.CharField(default='appointment_confirmation_universal', help_text='Hospital-specific template name for appointment confirmation', max_length=150),
        ),
        migrations.AddField(
            model_name='whatsappconfig',
            name='hospital_phone_num',
            field=models.CharField(default='', help_text='Hospital WhatsApp number used in CTA buttons and bot assignment', max_length=20),
        ),
        migrations.AddField(
            model_name='whatsappconfig',
            name='webhook_url',
            field=models.URLField(blank=True, help_text='Webhook URL registered for this hospital (optional override)', max_length=500, null=True),
        ),
    ]
