# Generated by Django 4.2.14 on 2025-09-26 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_notifications', '0004_whatsappconfig_confirmation_template_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whatsappconfig',
            name='confirmation_template',
        ),
        migrations.RemoveField(
            model_name='whatsappconfig',
            name='hospital_phone_num',
        ),
        migrations.RemoveField(
            model_name='whatsappconfig',
            name='webhook_url',
        ),
        migrations.AddField(
            model_name='whatsappconfig',
            name='template_confirmation',
            field=models.CharField(default='appointment_confirmation_universal', help_text='Template name for appointment confirmations', max_length=150),
        ),
        migrations.AddField(
            model_name='whatsappconfig',
            name='template_followup',
            field=models.CharField(default='followup_reminder_universal', help_text='Template name for follow-up reminders', max_length=150),
        ),
        migrations.AddField(
            model_name='whatsappconfig',
            name='template_reschedule',
            field=models.CharField(default='appointment_reschedule_universal', help_text='Template name for appointment reschedules', max_length=150),
        ),
        migrations.AddField(
            model_name='whatsappconfig',
            name='webhook_confirmation',
            field=models.URLField(blank=True, help_text='Webhook URL for confirmation messages', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='whatsappconfig',
            name='webhook_followup',
            field=models.URLField(blank=True, help_text='Webhook URL for follow-up messages', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='whatsappconfig',
            name='webhook_reschedule',
            field=models.URLField(blank=True, help_text='Webhook URL for reschedule messages', max_length=500, null=True),
        ),
    ]
