# Generated by Django 4.2.14 on 2025-09-26 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_hospitaluser_consult_message_template_and_more'),
        ('whatsapp_notifications', '0005_remove_whatsappconfig_confirmation_template_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whatsappconfig',
            name='template_confirmation',
        ),
        migrations.RemoveField(
            model_name='whatsappconfig',
            name='template_followup',
        ),
        migrations.RemoveField(
            model_name='whatsappconfig',
            name='template_reschedule',
        ),
        migrations.RemoveField(
            model_name='whatsappconfig',
            name='webhook_confirmation',
        ),
        migrations.RemoveField(
            model_name='whatsappconfig',
            name='webhook_followup',
        ),
        migrations.RemoveField(
            model_name='whatsappconfig',
            name='webhook_reschedule',
        ),
        migrations.CreateModel(
            name='WhatsappTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_type', models.CharField(choices=[('confirmation', 'Confirmation'), ('reschedule', 'Reschedule'), ('followup', 'Follow-up')], max_length=50)),
                ('template_name', models.CharField(max_length=150)),
                ('webhook_url', models.URLField(blank=True, max_length=500, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.hospital')),
            ],
            options={
                'unique_together': {('hospital', 'template_type')},
            },
        ),
    ]
