# Generated by Django 4.2.14 on 2025-09-29 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
        ('core', '0005_hospitaluser_consult_message_template_and_more'),
        ('whatsapp_notifications', '0006_remove_whatsappconfig_template_confirmation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsappmessagelog',
            name='provider_message_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='WhatsappInboundMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_message_id', models.CharField(max_length=255, unique=True)),
                ('from_number', models.CharField(max_length=20)),
                ('message_text', models.TextField()),
                ('event_type', models.CharField(choices=[('ACCEPTED', 'Accepted'), ('CANCELLED', 'Cancelled'), ('QUERY', 'Query'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.hospital')),
                ('in_reply_to', models.ForeignKey(blank=True, help_text='Links inbound to original outbound via context.message_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='whatsapp_notifications.whatsappmessagelog')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='patients.patient')),
            ],
        ),
    ]
