STANDARD_SYMPTOMS = {
        "General": [
            "Fever",
            "Fatigue",
            "Weight Loss",
            "Night Sweats",
            "Loss of Appetite",
        ],
        "Respiratory": [
            "Cough",
            "Shortness of Breath",
            "Chest Pain",
            "Wheezing",
            "Sputum Production",
        ],
        "Cardiovascular": [
            "Palpitations",
            "Chest Tightness",
            "Swelling of Legs",
            "Dizziness",
            "Syncope (Fainting)",
        ],
        "Gastrointestinal": [
            "Abdominal Pain",
            "Nausea",
            "Vomiting",
            "Diarrhea",
            "Constipation",
            "Blood in Stool",
        ],
        "Neurological": [
            "Headache",
            "Seizures",
            "Weakness",
            "Numbness",
            "Tremors",
            "Confusion",
        ],
        "Musculoskeletal": [
            "Joint Pain",
            "Muscle Pain",
            "Back Pain",
            "Stiffness",
            "Swelling",
        ],
        "Dermatological": [
            "Rash",
            "Itching",
            "Redness",
            "Swelling",
            "Ulcer",
        ],
        "Genitourinary": [
            "Burning Urination",
            "Frequent Urination",
            "Blood in Urine",
            "Pelvic Pain",
            "Discharge",
        ],
        "ENT": [
            "Sore Throat",
            "Ear Pain",
            "Hearing Loss",
            "Nasal Congestion",
            "Runny Nose",
        ],
        "Psychiatric": [
            "Depressed Mood",
            "Anxiety",
            "Insomnia",
            "Hallucinations",
            "Memory Loss",
        ],
    }