# Generated by Django 5.1.3 on 2025-07-17 00:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("appointments", "0001_initial"),
        ("core", "0001_initial"),
        ("doctors", "0001_initial"),
        ("drugs", "0001_initial"),
        ("patients", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PrescriptionMaster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("notes_history", models.TextField(blank=True)),
                ("notes_symptoms", models.TextField(blank=True)),
                ("notes_findings", models.TextField(blank=True)),
                ("general_advice", models.TextField(blank=True)),
                ("prescribed_on", models.DateTimeField(auto_now_add=True)),
                (
                    "appointment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="appointments.appointmentdetails",
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="doctors.doctor"
                    ),
                ),
                (
                    "hospital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.hospital"
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="patients.patient",
                    ),
                ),
            ],
            options={
                "db_table": "prescription_master",
                "ordering": ["-prescribed_on"],
                "unique_together": {("hospital", "patient", "prescribed_on", "doctor")},
            },
        ),
        migrations.CreateModel(
            name="PrescriptionLog",
            fields=[
                ("log_id", models.AutoField(primary_key=True, serialize=False)),
                ("drug_name", models.CharField(max_length=255)),
                ("composition", models.TextField(blank=True)),
                ("frequency", models.CharField(blank=True, max_length=100)),
                ("duration", models.CharField(blank=True, max_length=100)),
                ("notes", models.TextField(blank=True)),
                ("changed_by", models.CharField(max_length=100)),
                ("changed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "Create"),
                            ("update", "Update"),
                            ("delete", "Delete"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="doctors.doctor",
                    ),
                ),
                (
                    "hospital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.hospital"
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="patients.patient",
                    ),
                ),
                (
                    "prescription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="prescription.prescriptionmaster",
                    ),
                ),
            ],
            options={
                "db_table": "prescription_log",
                "ordering": ["-changed_at"],
            },
        ),
        migrations.CreateModel(
            name="PrescriptionItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("brand_name", models.CharField(max_length=255)),
                ("composition", models.TextField(blank=True)),
                ("dosage", models.CharField(blank=True, max_length=100)),
                ("frequency", models.CharField(blank=True, max_length=100)),
                ("duration", models.CharField(blank=True, max_length=100)),
                (
                    "drug",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="drugs.drug",
                    ),
                ),
                (
                    "prescription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="prescription.prescriptionmaster",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PrescriptionDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("drug_name", models.CharField(max_length=255)),
                ("composition", models.TextField(blank=True)),
                ("dosage", models.CharField(blank=True, max_length=100)),
                ("frequency", models.CharField(blank=True, max_length=100)),
                ("duration", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "hospital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.hospital"
                    ),
                ),
                (
                    "prescription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="details",
                        to="prescription.prescriptionmaster",
                    ),
                ),
            ],
            options={
                "db_table": "prescription_details",
                "ordering": ["drug_name"],
                "unique_together": {("prescription", "drug_name")},
            },
        ),
    ]
