# Generated by Django 5.1.3 on 2025-07-29 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prescription", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="prescriptiondetails",
            name="food_order",
            field=models.CharField(
                blank=True,
                choices=[("before", "Before Meal"), ("after", "After Meal")],
                default="after",
                help_text="Take before or after meals",
                max_length=6,
            ),
        ),
        migrations.AddField(
            model_name="prescriptionlog",
            name="food_order",
            field=models.CharField(
                blank=True,
                choices=[("before", "Before Meal"), ("after", "After Meal")],
                default="after",
                help_text="Take before or after meals",
                max_length=6,
                null=True,
            ),
        ),
        migrations.DeleteModel(
            name="PrescriptionItem",
        ),
    ]
