# Generated by Django 4.2.14 on 2025-11-18 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0002_prescriptiondetails_food_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescriptionmaster',
            name='diagnosis',
            field=models.TextField(blank=True),
        ),
    ]
