# Generated by Django 4.2.14 on 2025-11-22 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0008_alter_appointmentauditlog_token_num'),
        ('core', '0007_alter_hospital_slug'),
        ('doctors', '0003_doctor_consult_message_template_and_more'),
        ('prescription', '0003_prescriptionmaster_diagnosis'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrescriptionDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_step', models.CharField(default='history', max_length=50)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('ai_suggestions', models.JSONField(blank=True, default=dict)),
                ('finalized', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointments.appointmentdetails')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors.doctor')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.hospital')),
            ],
            options={
                'db_table': 'prescription_draft',
                'ordering': ['-updated_at'],
                'unique_together': {('doctor', 'appointment')},
            },
        ),
    ]
