# Generated by Django 4.2.14 on 2025-11-24 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0008_alter_appointmentauditlog_token_num'),
        ('prescription', '0004_prescriptiondraft'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescriptiondraft',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appointments.appointmentdetails'),
        ),
    ]
