# Generated by Django 4.2.14 on 2025-11-26 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_doctor_consult_message_template_and_more'),
        ('prescription', '0005_alter_prescriptiondraft_appointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorHistoryTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors.doctor')),
            ],
            options={
                'ordering': ['label'],
            },
        ),
    ]
