# Generated by Django 4.2.14 on 2025-12-04 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0008_alter_appointmentauditlog_token_num'),
        ('prescription', '0006_doctorhistorytemplate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescriptionmaster',
            name='appointment',
            field=models.ForeignKey(blank=True, help_text='Optional – prescription is not tied to appointment', null=True, on_delete=django.db.models.deletion.SET_NULL, to='appointments.appointmentdetails'),
        ),
    ]
