# Generated by Django 4.2.14 on 2025-12-05 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0008_alter_appointmentauditlog_token_num'),
        ('prescription', '0007_alter_prescriptionmaster_appointment'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='prescriptionmaster',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='prescriptionmaster',
            name='is_revisit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='prescriptionmaster',
            name='previous_rx',
            field=models.ForeignKey(blank=True, help_text='If this prescription continues a previous one', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='followups', to='prescription.prescriptionmaster'),
        ),
        migrations.AlterField(
            model_name='prescriptionmaster',
            name='appointment',
            field=models.ForeignKey(blank=True, help_text='Prescription is not strictly tied to an appointment', null=True, on_delete=django.db.models.deletion.SET_NULL, to='appointments.appointmentdetails'),
        ),
    ]
