# Generated by Django 4.2.14 on 2026-01-31 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0008_alter_prescriptionmaster_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescriptiondetails',
            name='instructions',
            field=models.TextField(blank=True, help_text='Special instructions / SIG'),
        ),
    ]
