# Generated by Django 5.1.3 on 2025-07-17 00:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Drug",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("drug_name", models.CharField(max_length=255)),
                ("composition", models.TextField(blank=True, null=True)),
                ("dosage", models.CharField(blank=True, max_length=100, null=True)),
                ("frequency", models.CharField(blank=True, max_length=100, null=True)),
                ("duration", models.CharField(blank=True, max_length=100, null=True)),
                ("uses", models.TextField(blank=True, null=True)),
                ("side_effects", models.TextField(blank=True, null=True)),
                (
                    "manufacturer",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "hospital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.hospital"
                    ),
                ),
            ],
        ),
    ]
