# Generated by Django 5.1.3 on 2025-07-18 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        ("doctors", "0001_initial"),
        ("drugs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="drug",
            name="added_by_doctor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="doctors.doctor",
            ),
        ),
        migrations.AlterField(
            model_name="drug",
            name="hospital",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.hospital",
            ),
        ),
    ]
