# Generated by Django 5.1.3 on 2025-08-08 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctors", "0001_initial"),
        ("drugs", "0003_userpreset"),
    ]

    operations = [
        migrations.CreateModel(
            name="DrugTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="drug_templates",
                        to="doctors.doctor",
                    ),
                ),
                (
                    "drugs",
                    models.ManyToManyField(related_name="templates", to="drugs.drug"),
                ),
            ],
        ),
    ]
