# Generated by Django 5.1.3 on 2025-08-09 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctors", "0001_initial"),
        ("drugs", "0004_drugtemplate"),
    ]

    operations = [
        migrations.CreateModel(
            name="DoctorDrug",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("added_on", models.DateTimeField(auto_now_add=True)),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="selected_drugs",
                        to="doctors.doctor",
                    ),
                ),
                (
                    "drug",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="selected_by_doctors",
                        to="drugs.drug",
                    ),
                ),
            ],
            options={
                "ordering": ["drug__drug_name"],
                "unique_together": {("doctor", "drug")},
            },
        ),
    ]
