# Generated by Django 4.2.14 on 2026-01-03 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_doctor_consult_message_template_and_more'),
        ('drugs', '0006_drugtemplateitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drugtemplate',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='drugtemplate',
            name='drugs',
        ),
        migrations.CreateModel(
            name='DoctorDrugUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drug_name', models.CharField(max_length=255)),
                ('usage_count', models.PositiveIntegerField(default=0)),
                ('last_used_on', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drug_usage', to='doctors.doctor')),
            ],
            options={
                'indexes': [models.Index(fields=['doctor', '-usage_count'], name='drugs_docto_doctor__a643ca_idx'), models.Index(fields=['doctor', '-last_used_on'], name='drugs_docto_doctor__994884_idx')],
                'unique_together': {('doctor', 'drug_name')},
            },
        ),
    ]
