# Generated by Django 5.1.3 on 2025-07-17 00:08

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AppointmentDetails",
            fields=[
                ("appoint_id", models.AutoField(primary_key=True, serialize=False)),
                ("appointment_on", models.DateField(default=datetime.date.today)),
                (
                    "mobile_num",
                    models.CharField(
                        help_text="10-digit mobile number",
                        max_length=10,
                        validators=[
                            django.core.validators.RegexValidator(regex="^\\d{10}$")
                        ],
                    ),
                ),
                ("token_num", models.CharField(max_length=20)),
                ("que_pos", models.IntegerField()),
                ("eta", models.TimeField(blank=True, null=True)),
                (
                    "completed",
                    models.SmallIntegerField(
                        choices=[
                            (-1, "No Show"),
                            (0, "Registered"),
                            (1, "In Queue"),
                            (2, "Done"),
                        ],
                        default=0,
                        help_text="Appointment status",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "appointment_details",
                "ordering": ["-appointment_on", "doctor"],
            },
        ),
    ]
