# Generated by Django 5.1.3 on 2025-07-17 00:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("appointments", "0001_initial"),
        ("billing", "0001_initial"),
        ("core", "0001_initial"),
        ("doctors", "0001_initial"),
        ("patients", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointmentdetails",
            name="doctor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="doctors.doctor"
            ),
        ),
        migrations.AddField(
            model_name="appointmentdetails",
            name="hospital",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.hospital"
            ),
        ),
        migrations.AddField(
            model_name="appointmentdetails",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="patients.patient"
            ),
        ),
        migrations.AddField(
            model_name="appointmentdetails",
            name="payment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="billing.paymentmaster"
            ),
        ),
        migrations.AddIndex(
            model_name="appointmentdetails",
            index=models.Index(
                fields=["appointment_on"], name="appointment_appoint_e31e9c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="appointmentdetails",
            index=models.Index(
                fields=["doctor"], name="appointment_doctor__c98d32_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="appointmentdetails",
            index=models.Index(
                fields=["payment"], name="appointment_payment_15eb7f_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="appointmentdetails",
            unique_together={("appointment_on", "patient", "doctor", "hospital")},
        ),
    ]
