# Generated by Django 5.1.3 on 2025-08-02 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0004_alter_appointmentdetails_completed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointmentdetails",
            name="completed",
            field=models.SmallIntegerField(
                choices=[
                    (2, "No Show"),
                    (-1, "Registered"),
                    (0, "In Queue"),
                    (1, "Done"),
                ],
                default=-1,
                help_text="Appointment status",
            ),
        ),
    ]
