# Generated by Django 5.1.3 on 2025-08-07 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0005_alter_appointmentdetails_completed"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointmentdetails",
            name="called",
            field=models.BooleanField(default=False),
        ),
    ]
