# Generated by Django 4.2.14 on 2025-09-25 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_hospitaluser_consult_message_template_and_more'),
        ('patients', '0001_initial'),
        ('doctors', '0003_doctor_consult_message_template_and_more'),
        ('appointments', '0006_appointmentdetails_called'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('token_num', models.IntegerField()),
                ('que_pos', models.IntegerField()),
                ('eta', models.TimeField(blank=True, null=True)),
                ('completion_time', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointments.appointmentdetails')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors.doctor')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.hospital')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
            ],
        ),
    ]
