# Generated by Django 4.2.14 on 2025-09-25 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0007_appointmentauditlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentauditlog',
            name='token_num',
            field=models.CharField(max_length=10),
        ),
    ]
