# Generated by Django 4.2.14 on 2025-12-07 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0008_alter_appointmentauditlog_token_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentdetails',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointmentdetails',
            name='queue_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
