# Generated by Django 4.2.14 on 2025-09-06 15:28

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patients', '0001_initial'),
        ('appointments', '0006_appointmentdetails_called'),
        ('core', '0005_hospitaluser_consult_message_template_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientVital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height_cm', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('30.00'))])),
                ('weight_kg', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('1.00'))])),
                ('bmi', models.DecimalField(decimal_places=2, editable=False, max_digits=5)),
                ('temperature_c', models.DecimalField(decimal_places=1, help_text='°C', max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('30.0')), django.core.validators.MaxValueValidator(Decimal('45.0'))])),
                ('bp_systolic', models.PositiveSmallIntegerField(help_text='mmHg', validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(260)])),
                ('bp_diastolic', models.PositiveSmallIntegerField(help_text='mmHg', validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(180)])),
                ('spo2_percent', models.PositiveSmallIntegerField(help_text='%', validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(100)])),
                ('pulse_bpm', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(220)])),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appointments.appointmentdetails')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.hospital')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vitals', to='patients.patient')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['hospital', 'patient', 'recorded_at'], name='vitals_pati_hospita_6d4e2b_idx')],
            },
        ),
    ]
