# Generated by Django 5.1.3 on 2025-07-17 00:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mobile_num", models.BigIntegerField()),
                ("contact_name", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "hospital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.hospital"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("patient_name", models.CharField(max_length=255)),
                ("age_years", models.PositiveIntegerField()),
                ("age_months", models.PositiveIntegerField(default=0)),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                        max_length=1,
                    ),
                ),
                (
                    "referred_by",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="patients",
                        to="patients.contact",
                    ),
                ),
                (
                    "hospital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.hospital"
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="contact",
            index=models.Index(
                fields=["mobile_num"], name="patients_co_mobile__301775_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="contact",
            unique_together={("mobile_num", "hospital")},
        ),
        migrations.AddIndex(
            model_name="patient",
            index=models.Index(
                fields=["contact"], name="patients_pa_contact_04128b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="patient",
            index=models.Index(
                fields=["hospital"], name="patients_pa_hospita_dc25dd_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="patient",
            unique_together={("contact", "patient_name", "hospital")},
        ),
    ]
