# Generated by Django 4.2.14 on 2025-11-09 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_patient_dob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='age_months',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='age_years',
        ),
    ]
