# Generated by Django 5.1.3 on 2025-07-17 00:08

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Doctor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("doctor_name", models.CharField(max_length=255)),
                (
                    "doc_mobile_num",
                    models.CharField(
                        max_length=10,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a valid 10-digit mobile number",
                                regex="^\\d{10}$",
                            )
                        ],
                    ),
                ),
                ("average_time_minutes", models.PositiveIntegerField()),
                ("fees", models.PositiveIntegerField()),
                ("start_time", models.TimeField(default=datetime.time(18, 0))),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "hospital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.hospital"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Doctors",
                "ordering": ["doctor_name"],
                "indexes": [
                    models.Index(
                        fields=["hospital"], name="doctors_doc_hospita_823fc1_idx"
                    ),
                    models.Index(
                        fields=["doc_mobile_num"], name="doctors_doc_doc_mob_e7ab4b_idx"
                    ),
                ],
                "unique_together": {("doc_mobile_num", "hospital")},
            },
        ),
    ]
