# Generated by Django 4.2.14 on 2025-09-06 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_doctor_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='consult_message_template',
            field=models.CharField(default='Valid for {days} days or {visits} visits whichever is earlier', max_length=255),
        ),
        migrations.AddField(
            model_name='doctor',
            name='consult_validity_days',
            field=models.PositiveIntegerField(default=6),
        ),
        migrations.AddField(
            model_name='doctor',
            name='consult_validity_visits',
            field=models.PositiveIntegerField(default=2),
        ),
    ]
