# Generated by Django 4.2.14 on 2026-01-28 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_doctor_consult_message_template_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='primary_specialty',
            field=models.CharField(choices=[('general', 'General Practice'), ('medicine', 'General Medicine'), ('pediatrics', 'Pediatrics'), ('gynecology', 'Gynecology'), ('orthopedics', 'Orthopedics'), ('ophthalmology', 'Ophthalmology'), ('ent', 'ENT'), ('dermatology', 'Dermatology')], default='general', max_length=32),
        ),
        migrations.AddField(
            model_name='doctor',
            name='secondary_specialties',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
