# Generated by Django 4.2.14 on 2025-11-16 19:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0008_alter_appointmentauditlog_token_num'),
        ('core', '0007_alter_hospital_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('drugs', '0006_drugtemplateitem'),
        ('patients', '0003_remove_patient_age_months_remove_patient_age_years'),
        ('doctors', '0003_doctor_consult_message_template_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_type', models.CharField(choices=[('CLINICAL', 'Clinical Notes'), ('SUMMARY', 'Summary'), ('AI_SUMMARY', 'AI-Generated Summary')], max_length=20)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visit_notes', to='appointments.appointmentdetails')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_visit_notes', to=settings.AUTH_USER_MODEL)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.hospital')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['hospital', 'patient'], name='visit_works_hospita_73fd57_idx')],
            },
        ),
        migrations.CreateModel(
            name='VisitDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('LAB', 'Lab Report'), ('RAD', 'Radiology Report'), ('RX_OLD', 'Old Prescription'), ('DISCH', 'Discharge Summary'), ('OTHER', 'Other')], max_length=20)),
                ('file', models.FileField(upload_to='visit_documents/%Y/%m/%d/')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visit_documents', to='appointments.appointmentdetails')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.hospital')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_visit_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['hospital', 'patient'], name='visit_works_hospita_546fe2_idx'), models.Index(fields=['appointment'], name='visit_works_appoint_2ac0a8_idx')],
            },
        ),
        migrations.CreateModel(
            name='PrescriptionTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('items_json', models.JSONField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors.doctor')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.hospital')),
            ],
            options={
                'ordering': ['doctor', 'name'],
                'unique_together': {('hospital', 'doctor', 'name')},
            },
        ),
        migrations.CreateModel(
            name='FavoriteDrug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors.doctor')),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drugs.drug')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.hospital')),
            ],
            options={
                'indexes': [models.Index(fields=['hospital', 'doctor'], name='visit_works_hospita_27d0e1_idx')],
                'unique_together': {('hospital', 'doctor', 'drug')},
            },
        ),
    ]
