# Generated by Django 4.2.14 on 2025-11-17 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visit_workspace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitdocument',
            name='ocr_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='visitnote',
            name='source',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='visitdocument',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='visit_documents/%Y/%m/%d/'),
        ),
    ]
