# Generated by Django 4.2.14 on 2025-11-18 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visit_workspace', '0002_visitdocument_ocr_text_visitnote_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitdocument',
            name='summary_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
