# Generated by Django 4.2.14 on 2025-11-30 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visit_workspace', '0003_visitdocument_summary_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitdocument',
            name='ai_summary_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
